name: Manually deploy fetch-abstract-robot to Azure Container Apps - production

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "Image tag to deploy (leave empty to use latest commit SHA - recommended)"
        required: false

permissions:
  contents: read

jobs:
  build-and-deploy-production:
    runs-on: ubuntu-latest
    environment: production

    env:
      IMAGE_NAME: fetch-abstract-robot-production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set outputs
        id: vars
        run: |
          sha_short=$(git rev-parse --short HEAD)
          unique_tag="${sha_short}-prod"
          echo "unique_tag=${unique_tag}" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        id: buildpush
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REPOSITORY_LOGIN_SERVER }}
          username: ${{ secrets.DEPLOYMENT_CLIENT_ID }}
          password: ${{ secrets.DEPLOYMENT_CLIENT_SECRET }}
        env:
          DOCKER_BUILDKIT: 1
      - run: |
          export TAG=${{ github.event.inputs.imageTag || steps.vars.outputs.unique_tag }}
          docker build -t ${{ secrets.REPOSITORY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${TAG} .
          docker push ${{ secrets.REPOSITORY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${TAG}
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name ${{ secrets.CONTAINER_APP_NAME_PRODUCTION }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ secrets.REPOSITORY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.buildpush.outputs.TAG }}
